---
- src: git+git@github.com:chatid/ansible-docker.git
  version: master

- src: git+git@github.com:chatid/ansible-consul-template.git
  version: master

- src: git+git@github.com:jdauphant/ansible-role-nginx.git
  version: master
  name: jdauphant.nginx

- src: git+git@github.com:Stouts/Stouts.python.git
  version: 2.0.3
