---
- name: registry | ensure config destination directory exists
  file:
    path: "{{ docker_registry_config_dest | dirname }}"
    state: directory

- name: registry | generate registry configuration
  template:
    src: "{{ docker_registry_config_src }}"
    dest: "{{ docker_registry_config_dest }}"
  register: config

- name: registry | ensure registry root directory exists
  file:
    path: "{{ docker_registry_filesystem_root }}"
    state: directory
  when: not docker_registry_s3_backend

- name: registry | run registry container
  docker:
    name: "{{ docker_registry_container_name }}"
    image: "{{ docker_registry_container_image }}"
    restart_policy: "{{ docker_registry_container_restart_policy }}"
    volumes:
      - "{{ docker_registry_filesystem_root }}:{{ docker_registry_filesystem_root }}"
      - "{{ docker_registry_config_dest }}:{{ docker_registry_config_dest }}"
    state: "{{ 'restarted' if config.changed else 'started' }}"