---
version: 0.1
log:
  level: debug
  formatter: text

storage:
  delete:
    enabled: yes
  cache:
    blobdescriptor: inmemory
{% if docker_registry_s3_backend %}
  s3:
    region: "{{ ec2_region }}"
    bucket: "{{ docker_registry_s3_bucket }}"
    encrypt: yes
    secure: yes
    v4auth: yes
    chunksize: 5242880
{% else %}
  filesystem:
    rootdirectory: /var/lib/registry
{% endif %}

{% if docker_registry_tls %}
auth:
  htpasswd:
    realm: "{{ docker_registry_auth_realm }}"
    path: /etc/docker/registry/htpasswd
{% endif %}

http:
  addr: 0.0.0.0:5000
  host: "https://{{ docker_registry_http_host }}:5000"
  secret: "{{ docker_registry_http_secret }}"
{% if docker_registry_tls %}
  tls:
    certificate: /etc/docker/registry/docker-registry.crt
    key: /etc/docker/registry/docker-registry.key
{% endif %}
  headers:
    X-Content-Type-Options: [nosniff]

redis:
  addr: localhost:6379